"""add delete_account column to users

Revision ID: f1d91d128e59
Revises: 
Create Date: 2025-08-10 18:04:33.748923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d91d128e59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'books', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('delete_account', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'delete_account')
    op.drop_constraint(None, 'books', type_='foreignkey')
    # ### end Alembic commands ###
